version: "3.9"
services:
    redis:
      container_name: redis
      build: ./redis/.
      image: amirmarmor/seawise_redis
      privileged: true
      ports:
        - "6379:6379"
      volumes:
        - ../data/redis:/data
      restart: always
    client:
      container_name: client
      build:
        context: ./guifrontend
      image: amirmarmor/seawise_client
      environment:
        - BACKEND_HOST=backend
      ports:
        - "3000:3000"
      depends_on:
        - backend
