version: "3.9"
services:
  redis:
    container_name: redis
    build: ./redis/.
    image: amirmarmor/seawise_redis
    privileged: true
    ports:
      - "6379:6379"
    volumes:
      - ../data/redis:/data
    restart: always
