FROM yummygooey/raspbian-buster as golang

RUN apt-get update
RUN apt-get install wget -y
RUN mkdir /tempgo

WORKDIR /tempgo
COPY ./go1.16.8.linux-armv6l.tar.gz ./
RUN tar -C /usr/local -xzf go1.16.8.linux-armv6l.tar.gz

RUN echo "PATH=$PATH:/usr/local/go/bin; GOPATH=$HOME/go" >> $HOME/.bashrc
RUN cat $HOME/.bashrc
RUN source $HOME/.bashrc

CMD ["go", "version"]

